### ISSUE TITLE
Add Clothing Category

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#106]
Sustainable Living is full of clothes, and we've got more to add. 

Also Tentree.com has loads of sustainable clothing, especially TENCEL/lyocell which [is awesome](https://www.saintbasics.com/en/blogs/blog/the-real-thing/). Mention both of that.

It would be helpful to have an intro that explains different kinds of natural materials, including modal, rayon, bamboo, hemp, cotton, wool, silk, linen, viscose, cupro, etc.

**Comment by jmcdona1d** [comment]
Would love to work on this for you. Can you please assign it to me if nobody else is currently working on it?

**Comment by HeidiHansen** [comment]
I assigned it to you.  Thanks James! =)

**Comment by philsturgeon** [comment]
@jmcdona1d thanks for volunteering! Get it done in 48 hours and I've got 100 trees and 3 tonnes to go in your offset earth account, or I'll throw it in mine in your name. offset.earth/philsturgeon

**Comment by mbifulco** [comment]
🙌  I'll double down on that - another 100 trees and 3 tonnes if it's done in 48 hours.  

This is good timing for me, too. I've been on the hunt for new socks... these guys look like they'd make a good addition to the category: https://www.arvingoods.com/

**Comment by mbifulco** [comment]
@jmcdona1d give a shout if you need any help figuring this stuff out - I did a major update to the site recently, so this stuff is still fresh.

**Comment by jmcdona1d** [comment]
@mbifulco Thanks, I think I should be good though - just finishing up and adding some more links
