### ISSUE TITLE
Report Greenwashing

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#109]
We need to figure out an approach for people to report greenwashing. It could be a link to a form, or an email us link, or whatever. 

We’ve done a fair amount of research on every link that we’ve added, or we wouldn’t have added it, but if we made a mistake (or a company changes course) we need to know that a link should be removed ASAP.

**Comment by mbifulco** [comment]
@philsturgeon I find lots of the greenwashing discussion to be really helpful, too.  It might be good to add some article pages / short form blog posts to the site to talk about specific instances of greenwashing.

**Comment by philsturgeon** [comment]
I'll write an article and we can mention it, but I have changed my mind on the necessity of this as a feature.
