### ISSUE TITLE
Header dropdown menu repeat twice

### ISSUE THREAD

**Issue by cheralathann** [philsturgeon/awesome-earth#110]
Home owner link repeat twice on the dropdown header menu

<img width="382" alt="Screenshot 2020-01-07 at 7 04 50 PM" src="https://user-images.githubusercontent.com/15264559/71899539-f76ed700-3181-11ea-8ab2-32fe41c4a452.png">

Change the title to Land owner on Header.jsx

**Comment by philsturgeon** [comment]
Thank you, done!
