### ISSUE TITLE
Recent Links

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#118]
I've been throwing new links in at the bottom, which means we can do a "recent links" just by popping a few off the end. Let's get this up on the homepage somehow.

**Comment by ijpatricio** [comment]
![screencapture-localhost-8000-2020-01-27-21_40_07](https://user-images.githubusercontent.com/26031459/73216472-f4964f00-414d-11ea-8ff5-0b566318b7b3.png)

**Comment by philsturgeon** [comment]
@ijpatricio ahh just noticed this isn't _quite_ right. Its showing the last 5 but in the wrong order:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/67381/73345035-3cff5b00-427b-11ea-81a1-98d0d06fb5e2.png">


I just added seat61 but its at the bottom :D 

Could you add in the tags like you mentioned, and fix that, then use the `Closes #118` syntax in your next pull request?

**Comment by ijpatricio** [comment]
not getting. enough. sleep. :D :D 

ehhe no problem! will do that real soon
also, you mentioned something more... 

also, on #133 you mentioned:
```
Could we use this style for the existing links on categories and tags pages as a follow up PR? Also, yes add the tags as badges to this list and the categories list please.
```

so it will be different issue & PR, right?

**Comment by philsturgeon** [comment]
we dont need to worry about the paperwork just mush it into one PR if thats ok :D
