### ISSUE TITLE
Rename "Volunteering" category?

### ISSUE THREAD

**Issue by mbifulco** [philsturgeon/awesome-earth#123]
Not everything on the [volunteering](https://protect.earth/volunteering/) page is volunteering.  We should consider a different nomenclature for this page.  Maybe "Action" or "engagement", or "get involved"?

**Comment by philsturgeon** [comment]
Yep was thinking this once petitions and jobs went up. Everything on the site is "action" but "Participate" perhaps. Engagement is definitely a good one.

**Comment by philsturgeon** [comment]
Now we have a #138 category this seems less important. Let's focus on some of the other issues and maybe we need a Bouycotts in the future or similar.
