### ISSUE TITLE
Tweet new links as they're accepted

### ISSUE THREAD

**Issue by mbifulco** [philsturgeon/awesome-earth#124]
It would be great to use twitter to announce new links posted to the site.

We could use a cloud function triggered by a GitHook or a webhook from Netlify/CI, and tweet a link to the page containing the new link.

**Comment by philsturgeon** [comment]
I'm fine tweeting stuff out myself, I've got a buffer and it takes seconds. I don't want any time sucked out of other things which could have a bigger impact.
