### ISSUE TITLE
links.yaml data

### ISSUE THREAD

**Issue by michaelsbach** [philsturgeon/awesome-earth#147]
Hi, all. I am new to open-source and Gatsby (as well as React to a certain extent) so I apologize if this is out of place.

I am curious as to how the data in [data/links.yaml](https://github.com/philsturgeon/awesome-earth/blob/37df27ecfafd8af54fe54c3707a4856b6cc88696/src/data/links.yaml#L9-L28) is able to be used in the [components/RecentLinks](https://github.com/philsturgeon/awesome-earth/blob/37df27ecfafd8af54fe54c3707a4856b6cc88696/src/components/RecentLinks.jsx#L7). It seems like "links" is a global variable of some sort, defined by the base keyword "links" in the yaml file. Would this be a feature of Gatsby, or is there maybe a config js folder that itemizes the ENV/global variables?

EDIT: I was also trying to assign this Issue with a label of "question" but I wasn't able to find the button to do that.

**Comment by philsturgeon** [comment]
Hey @michaelsbach! This is done in a fairly conventional way for a Gatsby site, but its alien if you're new to it. I was recently in your shoes :) 

In `gatsby-node.js` we create the links property https://github.com/philsturgeon/awesome-earth/blob/37df27ecfafd8af54fe54c3707a4856b6cc88696/gatsby-node.js#L102

This links property is then accessible in the RecentLinks component. Not global, just passed through.

**Comment by philsturgeon** [comment]
It's basically this https://www.gatsbyjs.org/tutorial/part-seven/

If you have any questions feel free to start off a PR and see how far you can get, I'll be more than happy to help you out with contributions even if we gotta do some learning on the way!
