### ISSUE TITLE
Can we present/display these projects in a more intuitive way?

### ISSUE THREAD

**Issue by sbutler-gh** [philsturgeon/awesome-earth#151]
Over the years, I've been collecting similar resources  -- but after getting frustrated with how difficult it is to intuitively search projects in a document, I migrated them to a map:

https://miro.com/welcomeonboard/PgGvqc9QgNnvxJPdM5wdwGyp6x8N690D2JDVr91KzyMDSZwluMEwxFz04W5dZzGK

Any interest in creating a similar interface with the Awesome Earth repository?

Best case, it could be an automated process -- so the projects are automatically organized, and the interface re-organizes itself when new categories are made and/or projects are added

**Comment by philsturgeon** [comment]
I think it depends very much on the intent of the project. We link to various maps, which help you find reforestation efforts near you, where coal plants are to protest, where people are considering expanding airports, etc. I don't know what use case a map of everything would aim to serve.

We are trying to help folks around the world by limiting results to a specific country, but we have some tweaks to go with that (#83).

**Comment by sbutler-gh** [comment]
> I think it depends very much on the intent of the project. We link to various maps

@philsturgeon This isn't a geographical map, it's a map of projects across different categories:

https://miro.com/welcomeonboard/PgGvqc9QgNnvxJPdM5wdwGyp6x8N690D2JDVr91KzyMDSZwluMEwxFz04W5dZzGK

^ Not to say that is the best answer, but I feel it's a step in the right direction on creating more intuitive interfaces to search/browse through these types of repositories, as opposed to scrolling through documents and clicking links

As the interface becomes more intuitive, it becomes a more useful (and engaging) tool

**Comment by philsturgeon** [comment]
I can't see that link, it's protected. We've got an issue for adding search (#18) so let's chat about that over there, and we can figure out some more ideas in the slack chat we started. :)
