### ISSUE TITLE
Migrate links.yaml to Netlify CMS Collections

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#155]
Split links.yaml into a [NetlifyCMS collection](https://www.netlifycms.org/docs/collection-types/#folder-collections)

It would be easier to treat case by case, instead of having a
massive file that gets changed in every change under netlify-cms.

For instructions on setting this up in Gatsby, they've got a tutorial: https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/#setup

**Comment by rapzo** [comment]
The slug configuration might be useful as well, specially if a timestamp is, somewhat, useful for sorting
https://www.netlifycms.org/docs/configuration-options/#slug

**Comment by philsturgeon** [comment]
Looks like we're still using links.yaml in netlify-cms too, #156 just part of it? What do we do next? 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/67381/77073219-d67afb80-69e6-11ea-95bb-0c9214f8812a.png">

**Comment by rapzo** [comment]
This PR should fix all broken thingies. Sorry about that. I might have been using a cached version and was focused on having the admin working.
