### ISSUE TITLE
Where does banking fit in?

### ISSUE THREAD

**Issue by FloEdelmann** [philsturgeon/awesome-earth#166]
Should *finance* be a separate category? There are some sustainable banks (at least in Germany) that don't invest in the coal industry and other bad actors:

* [Tomorrow](https://www.tomorrow.one/en-de/) (Germany, English site+app available)
* [Triodos Bank](https://www.triodos.co.uk/) (UK, Netherlands, Belgium, Germany, Spain, France)
* [GLS Bank](https://www.gls.de/privatkunden/) (Germany)
* [EthikBank](https://www.ethikbank.de/) (Germany)

**Comment by philsturgeon** [comment]
Yeah we got a whole category for that! We keep track of everything on this new site: https://github.com/protect-earth/protect.earth

Then now and then I run a script which scrapes the api and brings them over here. :)
