### ISSUE TITLE
Replace “icons” with “availability” 

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#17]
Folks can shove emojis in the description if they want but all of the country/globe stuff should be replaced with two-character country code array, or “global” for anywhere.

We can pick the emojis from that on display, and this also gives us the ability to filter by availability in the future.

**Comment by eostrom** [comment]
Happy Hacktober! Would you welcome a PR for this? I have some time to work on it tomorrow.

**Comment by philsturgeon** [comment]
Yes please! The gatsby site is in there, gunfire the README I’ll be trimming that down to just some examples. Can you have a go at establishing which links are which countries and get flags displayed for them? If it’s too time consuming just focus on the mechanics and I’ll finish the research part. 🙌🏻

**Comment by eostrom** [comment]
I got eager and I'm mostly done already. PR coming soon!
