### ISSUE TITLE
New category: politics

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#19]
See which political movements nearby can help. US voting for the jones act repeal would help stop ships and trucks doing so much pointless logistics. Stuff like that.

**Comment by akashbhandwalkar** [comment]
I will try to work on this issue.

**Comment by UPstartDeveloper** [comment]
I will be happy to help as well!

**Comment by UPstartDeveloper** [comment]
The Climate Strike Coalition is the organization responsible for organizing the youth-led global protests in NYC last month. Here is the link to their political platform, not sure if they fit in with this project entirely but there may be some overlap of interests: https://strikewithus.org/#demands
