### ISSUE TITLE
Carosel on the homepage

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#21]
Every week or month or whenever we can change some images for large recommended projects, to push folks towards particular things.

**Comment by MichaelGee** [comment]
Sorry, do u mind explaining the "to push folks towards particular things." part a little. I dont really understand.

**Comment by philsturgeon** [comment]
Hey @MichaelGee, good question! So the homepage could show off new and interesting things, seasonal things, etc.

Thing of this as "featured" content. In plasticFreeJuly we'd show off zero waste plastic avoiding things, in Winter we show how to insulate and heat your home better, etc.
