### ISSUE TITLE
Changing Reforestation category OR Add a new one for Agriculture/Food

### ISSUE THREAD

**Issue by iam-Shashank** [philsturgeon/awesome-earth#30]
Some thoughts regarding categories.
Apart from Reforestation, many companies in the field of Agriculture/Food are also doing great work. 2 possible options: Add these two categories to Reforestation or make a new category so that  special emphasis on Reforestation stays put. Also, many projects involving forests might involve activities different from reforestation so one possible option is to change it to Vegetation to include more projects under it, avoiding category fragmentation.

**Comment by philsturgeon** [comment]
We’re about to swap from the readme being the source of truth to using the gatsby site which powers http://awesom.earth. If you put this content in links.yaml and categories.yaml then it can have multiple categories. I’d like to keep reforestation and sure let’s add agriculture too. Thank you for your contributions on this!

--
Phil Sturgeon
@philsturgeon

**Comment by iam-Shashank** [comment]
Yes, keeping reforestation makes sense.  Sorry, yaml files are alien to me, have no experience with them. Not a web dev. In the coming days, if I do learn about them, I'll make sure to do what you suggested.

**Comment by philsturgeon** [comment]
@iam-Shashank no worries, what sort of dev are you? They're a bit like TOML if you're familiar, and they're a superset of JSON. You can copy and paste code, and use http://www.yamllint.com/ to make sure whatever you're doing is valid. :)

**Comment by philsturgeon** [comment]
Do you have some ideas for links in this new agriculture/food category?

**Comment by philsturgeon** [comment]
Let me know if you think up a thing!

**Comment by iam-Shashank** [comment]
Hey, really sorry for the late response. Was busy with a few hackathons, college stuff( end of Semester rush, you know). I am a Machine Learning practitioner/learner, so not into web stuff. Regarding more ideas related to Agri, luckily, this AskHN was trending today (I haven't read it yet, decided to post it here, as soon as I found it.) [Link](https://news.ycombinator.com/item?id=21325138)
