### ISSUE TITLE
Category Images

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#39]
Lets get some fancy looking images to improve the look of the homepage now we dont have all the links on there.

**Comment by HeidiHansen** [comment]
Carbon Reduction
- https://stock.adobe.com/nl/images/carbon-dioxide-emissions-control-concept-3d-rendering-of-co2-cloud-on-fresh-spring-meadow-with-blue-sky-in-background/206053572

Cooking
- http://www.stoveteam.org/images/slides/kitchen1.jpg
- http://www.stoveteam.org/images/slides/ecocina_01.jpg

Community and Education

Green Energy
- https://stock.adobe.com/nl/images/photovoltaics-solar-panel-and-wind-turbines-generating-electricity-in-solar-power-station-alternative-energy-from-nature/125016564
- https://stock.adobe.com/nl/images/wind-turbine-with-solar-panels-and-sunset-concept-clean-energy/195603050
- https://stock.adobe.com/nl/images/wind-turbines-on-beautiful-sunny-summer-autumn-mountain-landsape-curvy-road-through-mountain-eolic-park-green-ecological-power-energy-generation-wind-farm-eco-field/239024879
- https://stock.adobe.com/nl/images/wind-turbine-farm-power-generator-in-beautiful-nature-landscape-for-production-of-renewable-green-energy-is-friendly-industry-to-environment-concept-of-sustainable-development-technology/279569595
- https://stock.adobe.com/nl/images/wind-turbines-on-the-mountain/215842794

Reforestation
- https://stock.adobe.com/nl/images/couple-planting-and-watering-a-tree-together-on-a-summer-day-in-park-volunteering-charity-people-and-ecology-environment-and-ecology-concept/191487976
- https://stock.adobe.com/nl/images/planting-stock-of-pine-trees-at-the-road/133051077
- https://stock.adobe.com/nl/images/reforestation-to-forest-protection-pine-tree-planted/137763804

Sustainable Lifestyle
- https://stock.adobe.com/nl/images/breakfast-vegan-bowls/172470354
- https://stock.adobe.com/nl/images/eco-bags-with-bamboo-cutlery-reusable-coffee-mug-and-water-bottle/285680496

Transportation
- https://bicycledutch.files.wordpress.com/2016/04/utrecht2016-08.jpg
- https://bicycledutch.files.wordpress.com/2018/01/cycling-figures01.jpg
- https://ecf.com/files/wp-content/uploads/2011/11/FamilyCycleTrain1.jpg
- https://stock.adobe.com/nl/images/traffic-light-for-bikes/71410509
- https://stock.adobe.com/nl/images/people-riding-bicycles-in-amsterdam-in-the-netherlands/172340512
- https://stock.adobe.com/nl/images/a-lot-of-bikes-on-parking-in-amsterdam-netherlands/222543525

Zero Waste
- https://stock.adobe.com/nl/images/banner-with-assortment-of-grain-products-and-pasta-in-glass-storage-containers-on-wooden-table-healthy-cooking-clean-eating-zero-waste-concept-balanced-dieting-food-copy-space/268365087
- https://stock.adobe.com/nl/images/food-containers-in-zero-waste-shop-filled-with-raw-food/243913200

Home Appliances
- https://stock.adobe.com/nl/images/funny-fat-man-sings-in-the-shower/250487903
- https://stock.adobe.com/nl/images/enthusiastic-tattooed-man-using-shower-head-as-his-microphone/247054539

**Comment by philsturgeon** [comment]
Thanks to the category markdown PR from @stephensamra (#42) we can get these images into category frontmatter with a new `image:` key. I’ll have a go at this in the morning. Comments welcome from folks about which images are best and if anyone gets this code done before me I won’t be awake for 8 hrs. 😅
