### ISSUE TITLE
Tag pages

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#40]
Blocked by #40 

Some of our categories should probably be tags, and in the future we want more landing pages for tag things. 

For now, lets just have a simple page with a list of things that exist for that tag. Copy the categories page entirely, we will differentiate them more later.

https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/

**Comment by StaleSpace** [comment]
I'll work on it 
can you guide me a bit what's need to be done?

**Comment by philsturgeon** [comment]
Basically we’d like to be able to tag links with various concepts that aren’t quite categories, then have a single landing page for them. 

It would be very similar to categories in fact. Mostly what’s in the tutorial I linked to, but each tag may or may not have a tag page src/content/tags/Foo.md and the data is in links.yaml with tags: [foo, bar]

Does that make sense? 

--
Phil Sturgeon
@philsturgeon

**Comment by philsturgeon** [comment]
@StaleSpace hey, still fancy taking a swing at this? @stephensamra has also offered his services. :)

**Comment by mats-codes** [comment]
Is there any further help required regarding this issue?

**Comment by philsturgeon** [comment]
@mats-codes this is tricky, @StaleSpace offered to work on it 8 days ago and id be fine waiting much longer for this to be done (I appreciate any help I get however long it takes) but it also seems like there is a lot of interest from other people in getting it done sooner. 

First PR wins? I'll donate 100 trees for each person who makes a PR whichever one ends up getting merged. @mats-codes think you could get it done?
