### ISSUE TITLE
More reforestation projects

### ISSUE THREAD

**Issue by Seldaek** [philsturgeon/awesome-earth#44]
Crowther Lab (who do a lot of climate research and published a few interactie maps) has a page listing a dozen reforestation projects, might be good to copy https://www.crowtherlab.com/get-involved/

**Comment by fridaland** [comment]
Hey there :wave:
Would love to help out here. Are we looking to add the exact list in Crowther Lab?

**Comment by bagshik** [comment]
Oh I forgot to write a comment here, well the more the merrier :) Yeah, I guess we can search their map / list for missing projects and add them to the repo's `links.yaml`

**Comment by fridaland** [comment]
All good if you've already started @bagshik. :) I can contribute to another issue!

**Comment by philsturgeon** [comment]
@fridaland happy to get some more, I’m focusing my efforts on #39

**Comment by philsturgeon** [comment]
Great I got a few of these! If anyone still wants to help theres plenty more issues to be tackled! :D
