### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#50]
We'll need a proper redesign as this starter one is being stretched as far as @HeidiHansen and I can get it. Paging @thatleeguy! 😎 

## Home

![Home](https://user-images.githubusercontent.com/67381/66702142-98293400-ed04-11e9-98bd-231437167f76.png)

The homepage, not too far off from what we got now but better grid, hopefully some sort of logo and hero situation, top nav and a newsletter signup box. Maybe https://emailoctopus.com/ for the newsletter.

## Category Page

![Category](https://user-images.githubusercontent.com/67381/66702139-98293400-ed04-11e9-955e-aedbaa6db828.png)

It would be good to pick out a few great links to feature, give them an image, etc and then the rest of them smaller at the bottom. 

## Generic Page 

![Generic Text Page](https://user-images.githubusercontent.com/67381/66702140-98293400-ed04-11e9-8211-9818cc8995cc.png)

We need to be able to add single pages for About, Contributing, and whatever else comes up.

**Comment by ElRaymond0** [comment]
I can take a crack at this if you want? Do you have anything specific for colours or would you like to keep the same colours as the current design?

Within the category page will there be a maximum/minimum of three featured links with images?

**Comment by philsturgeon** [comment]
Thank you @ElRaymond0, but @thatleeguy mentioned he would do this and might already be working on something. Could you maybe help us get the HTML and Gatsby done for the links page? Then Lee will only have to tackle the visual aspects.

**Comment by ElRaymond0** [comment]
@philsturgeon Sure no worries! If @thatleeguy is taking a look that's not a problem, if you need some help with the Gatsby/html I could give that a go or jump on another issue

**Comment by philsturgeon** [comment]
Ok we're off! https://bitbucket.org/thatleeguy/awesom.earth/ 

This is a great start and will help us out a lot. I started the integration in the [`redesign` branch](https://github.com/philsturgeon/awesome-earth/tree/redesign) but I've hit a few problems.

1. We lost the carosel, which seems like a shame. 
2. Category mockups have feature items but i dont think we have that now
3. search takes up a lot of space at the top and I think we need to show people content before we get them to search, so maybe a little search input top right would be ok like the mockup

@stephensamra do you think you could grab the source and have a go at this? I couldn't figure out how to get `vendor.css` copied across either so that's a difficult one.

**Comment by mbifulco** [comment]
Hey @philsturgeon - redesign sketches look great! I'm pulling down the branch to see if I can submit a PR or two to help it along.

I'm going to put in a vote in support of [removing the carousel](http://shouldiuseacarousel.com/).  They look a lot nicer than they work, unfortunately.

**Comment by philsturgeon** [comment]
Merged #93! It's not perfect but it's much better than what we had. All improvements welcome, and there is still lots to do with search #18 and improving country filters #83.
