### ISSUE TITLE
Shared layout

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#52]
Add a layout which wraps both index and category pages, with a simple top nav and a github ribbon:

```
<a href="https://github.com/philsturgeon/awesome-earth"><img width="149" height="149" src="https://github.blog/wp-content/uploads/2008/12/forkme_left_green_007200.png?resize=149%2C149" class="attachment-full size-full" alt="Fork me on GitHub" data-recalc-dims="1"></a>
```

**Comment by UPstartDeveloper** [comment]
May I please help with this?

**Comment by philsturgeon** [comment]
@UPstartDeveloper please! Do you think you could do it in the next few days?

**Comment by UPstartDeveloper** [comment]
I'll get started right now on the nav. I'll try to use Bootstrap for the website, since I just learned about the CSS framework this past few days at my college, Make School.

**Comment by UPstartDeveloper** [comment]
My sincerest apologies, this will take longer than I thought. I am unsure of how to combine my bootstrap knowledge with the current project setup currently to use React.

**Comment by ElRaymond0** [comment]
Hi @UPstartDeveloper one way of approaching this would be to look at creating a specific component which acts as a layout template. It simply dynamically wraps the component allowing for the layout to be reused. I could submit a PR for this issue if you wanted to take a look at this approach?

**Comment by UPstartDeveloper** [comment]
Thanks for the suggestion @ElRaymond0 ! Feel free to submit a PR. So far, I have been trying to figure out a way to use ReactStrap for the component, sorry for my lack of progress thus far.

**Comment by UPstartDeveloper** [comment]
Hey Philsturgeon/Awesome-Earth,
I’m really sorry for not getting back to you on this. It’s totally my fault
and I know it’s probably too late now, I just want you to know I didn’t
mean to cause you any inconvenience. Hope you will understand that I just
lost track of time.

Sincerely,
Zain Raza

**Comment by philsturgeon** [comment]
Not a problem at all @UPstartDeveloper! Please, this is a free site and eeryone is doing what they can when they can. Things come up and that's fine. This PR got done a little while ago we just forgot to close the ticket, so I'm glad you didn't do the work a second time only to find out it was done already! haha
