### ISSUE TITLE
Submissions Form

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#69]
Let people suggest their own links via a Netlify form. 

https://www.netlify.com/products/forms/

**Comment by stephensamra** [comment]
Hey 👋 I could take a look at this, I have some experience using Netlify forms. What fields would you like on the form?

**Comment by philsturgeon** [comment]
Should we just go with URL and checkboxes for the categories? Maybe countries too in case its not english and its tough to figure out how many potential countries the site is relevant to? 

Also I'll be in Dublin tomorrow, you around? :D Shoot me a message on me@πhilsturgeon.uk or https://twitter.com/philsturgeon/

**Comment by stephensamra** [comment]
Grand, will get working on that. Tomorrow suits me fine, I'll email you later today 👍
