### ISSUE TITLE
Select Your Country

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#71]
Let's take inspiration from this Spotify page, and have a select your country page. 

https://www.spotify.com/nl/select-your-country/

When you pick your country it will show up in our awesome new shared layout, maybe in a really simple footer. Again, just like spotify:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/67381/68201146-7e0c0a00-ffc1-11e9-8114-16e2ea718ff1.png">

If there is nothing available for a country, grey it out and make it not be a link. No point wasting peoples time if there is no content for that country.

**Comment by philsturgeon** [comment]
@stephensamra hey if you're up for a bigger one, I think this could be right up your alley. This will help us go international instead of being very UK-US-Dutchkinda.

**Comment by stephensamra** [comment]
@philsturgeon sounds good! When a country is selected do you want to do anything like show a page that lists everything by the selected country? Or just have it show up in the layout?

**Comment by philsturgeon** [comment]
@stephensamra agh sorry I missed this. I think it should act like a global filter, and the site should continue to function as it does but limiting the results. We should make this be clear somewhere, so folks dont wonder why there is nothing much around.

**Comment by stephensamra** [comment]
@philsturgeon no worries at all. Yea I think that sounds cool. Will try get something up this week.

**Comment by stephensamra** [comment]
@philsturgeon I have a wip of this that you can try out here: https://5dd5b35fe49197000886e70a--condescending-williams-490604.netlify.com/. If you scroll to the footer you should see an option to select a country.

I think the only thing left to do now is to filter the category pages/data by the selected country and maybe add an option to remove the selected country preference. If you have any thoughts so far, feel free to let me know.

**Comment by philsturgeon** [comment]
This is great! Please start off a PR so I can see, but yeah keep on trucking with this and update the category data, thank you. 

Btw #50 is almost ready :D
