### ISSUE TITLE
Category Descritions in SEO

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#80]
Currently the main website description is showing up in the SEO, Twitter cards, etc. but we should try and get a short description for each category (not the giant intro) into each.

**Comment by stephensamra** [comment]
This is what's currently showing when a category is shared (it's the category description). Do you want to have something shorter? We could add something to the YAML front-matter unless you have a better idea?

![image](https://user-images.githubusercontent.com/8583469/71550514-3eaed800-29ca-11ea-95ee-a75a3dd2e3a2.png)

**Comment by philsturgeon** [comment]
This is ok for now, but yeah we could get a shorter description in there and show it on the homepage too I think?
