### ISSUE TITLE
Front page images are very large

### ISSUE THREAD

**Issue by cebe** [philsturgeon/awesome-earth#95]
I just noticed that on the frontpage, the category images are way too big.

![Bildschirmfoto von »2019-12-23 09-29-30«](https://user-images.githubusercontent.com/189796/71345875-c75eeb80-2566-11ea-820a-26f40ae7fa82.png)

All of these are a lot bigger than they should be (pixel and byte size):

![Bildschirmfoto von »2019-12-23 09-30-25«](https://user-images.githubusercontent.com/189796/71345953-01c88880-2567-11ea-8649-f511ba54f045.png)

e.g. the carbon-reduction image is 7500x4935px and 1.73MB.

**Comment by philsturgeon** [comment]
Damn, there was a bit of magic doing auto-resizing but I guess that fell away in the redesign. 

@stephensamra can you tackle this one after Christmas? :D
